# Generated by Django 5.2.16 on 2026-07-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='公司')),
                ('email', models.EmailField(max_length=254, verbose_name='电子邮件')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='电话 / WhatsApp')),
                ('inquiry_type', models.CharField(choices=[('general', '一般咨询'), ('product', '产品咨询'), ('support', '技术支持'), ('cooperation', '商务合作'), ('other', '其他')], default='general', max_length=50, verbose_name='查询类型')),
                ('message', models.TextField(verbose_name='留言')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '客户留言',
                'verbose_name_plural': '客户留言',
                'ordering': ['-created_at'],
            },
        ),
    ]
