# Generated by Django 5.2.16 on 2026-07-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='inquiry_type',
            field=models.CharField(choices=[('sourcing', '商品采购'), ('oem', 'OEM / ODM'), ('logistics', '物流与运输'), ('wholesale', '批发 / 分销'), ('other', '其他')], default='general', max_length=50, verbose_name='查询类型'),
        ),
    ]
